Calculate sentence score: src/functions.cpp File Reference
functions.cpp File Reference
#include "functions.hpp"
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <time.h>
#include <algorithm>
#include <functional>
#include <map>
#include <set>
#include <random>
#include <string.h>
#include <chrono>
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/log/utility/setup/common_attributes.hpp>
Functions
void init_logging ()
This function helps in logging level.
void init_random_matrices (std::vector< std::bitset< 100 >> &matrices)
initializing random matrices
void read_dict_from_file (const std::string &dictionary_filename, std::vector< std::string > &dictionary)
reading dictionary from file
void read_text_from_file (const std::string &text_filename, std::vector< std::string > &text)
reading input text, stop words from file
void init_hashes (std::vector< size_t > &hashes, const std::hash< std::string > &hasher, const std::vector< std::string > &words)
calculating hashes of words stored in words
void correct_dict_hashes_and_extract_duplicates (std::vector< std::vector< size_t >> &duplicates, std::vector< size_t > &hashes)
finding duplicates and correcting dictionary hashes
void correct_text_hashes (std::vector< size_t > &text_hashes, const std::vector< std::string > &text, const std::vector< std::vector< size_t >> &duplicates, const std::vector< std::string > &dictionary)
correcting input text hashes, maybe there are duplicates
void hash_function (std::vector< std::pair< size_t, size_t >> &hash_table, const std::vector< size_t > &hashes)
hashing open adressing with linear probbing algorithm
void search_and_calculate_matrices (std::bitset< 100 > &output, std::map< std::string, size_t > &words_count, const std::vector< size_t > &text_single_term_hashes, const std::vector< size_t > &text_double_term_hashes, const std::vector< size_t > &text_triple_term_hashes, const std::vector< size_t > &stop_words_hashes, const std::vector< std::pair< size_t, size_t >> &hash_table, const std::vector< std::bitset< 100 >> &matrices, const std::vector< std::string > &dictionary)
correcting input text hashes, maybe there are duplicates
void extract_words_count (const std::map< std::string, size_t > &m)
void print_hash_table (const std::vector< std::pair< size_t, size_t >> &hash_table, size_t begin, size_t end)
void print_duplicates (const std::vector< std::vector< size_t >> &duplicates, const std::vector< std::string > &dictionary)
void print_matrix (const std::vector< size_t > &matrix)
void print_words (const std::vector< std::string > &dictionary)
void print_vector (const std::vector< size_t > &vector)
void print_bitset (const std::bitset< 100 > &bitset)
void print_bitset_vector (const std::bitset< 100 > &bitset)
bool contains_duplicates (std::vector< size_t > a)
bool contains_duplicates_h (std::vector< size_t > a)
void init_random_matrices (std::vector< std::vector< size_t >> &matrices)
void read_from_file (const std::string &text_filename, std::string &text)
Function Documentation
contains_duplicates()
bool contains_duplicates (std::vector< size_t > a)
Definition at line 426 of file functions.cpp.
 {
     if (a.size() < 2)
     {
         return false;
     }
     sort(a.begin(), a.end());
     //std::cout << a[a.size() - 1] << std::endl;
     //std::cout << a[0] << std::endl;
     for (int i = 0; i < a.size() - 1; i++)
     {
         if (a[i] == a[i + 1])
         {
             std::cout << a[i] << std::endl;
         }
     }
     return false;
 }
contains_duplicates_h()
bool contains_duplicates_h (std::vector< size_t > a)
Definition at line 445 of file functions.cpp.
 {
     if (a.size() < 2)
     {
         return false;
     }
     for (int i = 0; i < a.size() - 1; i++)
     {
         a[i] = a[i] % a.size();
     }
     sort(a.begin(), a.end());
     //std::cout << a[a.size() - 1] << std::endl;
     //std::cout << a[0] << std::endl;
     for (int i = 0; i < a.size() - 1; i++)
     {
         if (a[i] == a[i + 1])
         {
             std::cout << a[i] << std::endl;
         }
     }
     return false;
 }
correct_dict_hashes_and_extract_duplicates()
void correct_dict_hashes_and_extract_duplicates (std::vector< std::vector< size_t >> & duplicates, std::vector< size_t > & hashes)
finding duplicates and correcting dictionary hashes
Parameters
duplicates - contain words old hashes, indexes to the words with that hashes, and new hashes
hashes - hash of dictionary, contain hashed strings of each word in dictionary
Definition at line 171 of file functions.cpp.
References duplicates.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t size = hashes.size();
     std::map<size_t, size_t> m;
     if (size < 2)
     {
         return;
     }
     for (size_t i = 0; i < size; ++i)
     {
         m[hashes[i]] = 0;
     }
     for (size_t i = 0; i < size; ++i)
     {
         if (m[hashes[i]])
         {
             size_t temp = hashes[i];
             while (m[temp])
             {
                 temp++;
             }
             duplicates.push_back({ hashes[i], i, temp });
             hashes[i] = temp;
         }
         else
         {
             m[hashes[i]] = 1;
         }
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "correct_dict_hashes_and_extract_duplicates()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
correct_text_hashes()
void correct_text_hashes (std::vector< size_t > & text_hashes, const std::vector< std::string > & text, const std::vector< std::vector< size_t >> & duplicates, const std::vector< std::string > & dictionary)
correcting input text hashes, maybe there are duplicates
Parameters
text_hashes - hash of text, contain hashed strings of each word in text
text - contain all words in input text(maximum 500terms)
duplicates - contain words old hashes, indexes to the words with that hashes, and new hashes
dictionary - conatin all words in dictionary.txt
Definition at line 210 of file functions.cpp.
References duplicates, and text_size.
Referenced by main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t duplicate_size = duplicates.size();
     size_t text_size = text_hashes.size();
     for (size_t i = 0; i < duplicates.size(); ++i)
     {
         for (size_t j = 0; j < text_size; ++j)
         {
             if (text_hashes[j] == duplicates[i][0])
             {
                 if (text[j] == dictionary[duplicates[i][1]])
                 {
                     text_hashes[j] = duplicates[i][2];
                 }
             }
         }
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "correct_text_hashes()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
extract_words_count()
void extract_words_count (const std::map< std::string, size_t > & m)
Definition at line 327 of file functions.cpp.
Referenced by main().
 {
     typedef std::function<bool(std::pair<std::string, int>, std::pair<std::string, int>)> Comparator;
     Comparator compFunctor = [](std::pair<std::string, size_t> elem1 ,std::pair<std::string, size_t> elem2)
     {
         return elem1.second > elem2.second;
     };
     std::set<std::pair<std::string, int>, Comparator> setOfWords(
             m.begin(), m.end(), compFunctor);
     // Iterate over a set using range base for loop
     // It will display the items in sorted order of values
     for (std::pair<std::string, int> element : setOfWords)
         BOOST_LOG_TRIVIAL(info) << element.first << " :: " << element.second;
 }
hash_function()
void hash_function (std::vector< std::pair< size_t, size_t >> & hash_table, const std::vector< size_t > & hashes)
hashing open adressing with linear probbing algorithm
Parameters
hash_table - hash table contain hashes and indexes to the words in dictionary
hashes - hash of dictionary, contain hashed strings of each word in dictionary
Definition at line 236 of file functions.cpp.
References hash_table(), and words_count.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t words_count = hashes.size();
     for (size_t i = 0; i < words_count; ++i)
     {
         size_t index = hashes[i] % words_count;
         while (hash_table[index].first)
         {
             index = (index + 1) % words_count;
         }
         hash_table[index] = std::make_pair(hashes[i], i);
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "hash_function()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
init_hashes()
void init_hashes (std::vector< size_t > & hashes, const std::hash< std::string > & hasher, const std::vector< std::string > & words)
calculating hashes of words stored in words
Parameters
hasher - object that hashes words
words - all words that need to be hashed
Definition at line 136 of file functions.cpp.
References hasher.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t size = hashes.size();
     if (size == words.size() - 2)
     {
         for (size_t i = 0; i < size; ++i)
         {
             hashes[i] = hasher(words[i] + "-" +
                             words[i + 1] + "-" +
                             words[i + 2]);
         }
     }
     else if (size == words.size() - 1)
     {
         for (size_t i = 0; i < size; ++i)
         {
             hashes[i] = hasher(words[i] + "-" +
                             words[i + 1]);
         }
     }
     else
     {
         for (size_t i = 0; i < size; ++i)
         {
             hashes[i] = hasher(words[i]);
         }
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "init_hashes()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
init_logging()
void init_logging ()
This function helps in logging level.
Definition at line 22 of file functions.cpp.
Referenced by main().
 {
     logging::register_simple_formatter_factory<logging::trivial::severity_level, char>("Severity");
     logging::add_file_log(
         keywords::file_name = "logfile.log",
         keywords::format = "[%TimeStamp%] [%ThreadID%] [%Severity%] [%ProcessID%] [%LineID%] %Message%"
     );
     logging::core::get()->set_filter
     (
         logging::trivial::severity >= logging::trivial::trace
     );
     logging::add_common_attributes();
 }
init_random_matrices() [1/2]
void init_random_matrices (std::vector< std::bitset< 100 >> & matrices)
initializing random matrices
Parameters
matrices - vector of bitsets, contain all initialized matrices of length 100
Definition at line 39 of file functions.cpp.
References dict_size, and matrices().
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t dict_size = matrices.size();
     std::default_random_engine dre(std::random_device{}());
     std::uniform_int_distribution<long long> dist(0, (1ll << 50) - 1);
     for (size_t i = 0; i < dict_size; ++i)
     {
         matrices[i] = dist(dre);
         matrices[i] <<= 50;
         matrices[i] |= dist(dre);
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "init_random_matrices()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
init_random_matrices() [2/2]
void init_random_matrices (std::vector< std::vector< size_t >> & matrices)
Definition at line 470 of file functions.cpp.
References dict_size, matrices(), and matrix_size.
 {
     size_t dict_size = matrices.size();
     size_t matrix_size = matrices[0].size();
     for (size_t i = 0; i < dict_size; ++i)
     {
         for (size_t j = 0; j < matrix_size; ++j)
         {
             matrices[i][j] = rand() % 2;
         }
     }
 }
print_bitset()
void print_bitset (const std::bitset< 100 > & bitset)
Definition at line 405 of file functions.cpp.
 {
     for (size_t j = 0; j < 10; ++j)
     {
         for (size_t i = j * 10; i < j * 10 + 10; ++i)
         {
             std::cout << bitset[i] << " ";
         }
         std::cout << std::endl;
     }
 }
print_bitset_vector()
void print_bitset_vector (const std::bitset< 100 > & bitset)
Definition at line 417 of file functions.cpp.
 {
     for (size_t j = 0; j < bitset.size(); ++j)
     {
         std::cout << bitset[j];
     }
     std::cout << std::endl;
 }
print_duplicates()
void print_duplicates (const std::vector< std::vector< size_t >> & duplicates, const std::vector< std::string > & dictionary)
Definition at line 354 of file functions.cpp.
References duplicates.
 {
     for (int i = 0; i < duplicates.size(); ++i)
     {
         for (int j = 0; j < duplicates[0].size(); ++j)
         {
             if (j == 1)
             {
                 std::cout << "dictionary[" << duplicates[i][j] << "] = " << dictionary[duplicates[i][j]] << " ";
             }
             else
             {
                 std::cout << duplicates[i][j] << " ";
             }
         }
         std::cout << std::endl;
     }
 }
print_hash_table()
void print_hash_table (const std::vector< std::pair< size_t, size_t >> & hash_table, size_t begin, size_t end)
Definition at line 345 of file functions.cpp.
References hash_table().
 {
     for (size_t i = begin; i < end; ++i)
     {
         //std::cout << "hash = " << hash_table[i].first << "  index = " << hash_table[i].second << std::endl;
         std::cout << hash_table[i].first << " " << hash_table[i].second << std::endl;
     }
 }
print_matrix()
void print_matrix (const std::vector< size_t > & matrix)
Definition at line 375 of file functions.cpp.
 {
     for (size_t j = 0; j < 10; ++j)
     {
         for (size_t i = j * 10; i < j * 10 + 10; ++i)
         {
             std::cout << matrix[i] << " ";
         }
         std::cout << std::endl;
     }
 }
print_vector()
void print_vector (const std::vector< size_t > & vector)
Definition at line 396 of file functions.cpp.
 {
     for (size_t i = 0; i < vector.size(); ++i)
     {
         std::cout << vector[i];
     }
     std::cout << std::endl;
 }
print_words()
void print_words (const std::vector< std::string > & dictionary)
Definition at line 387 of file functions.cpp.
 {
     for (size_t i = 0; i < dictionary.size(); ++i)
     {
         std::cout << dictionary[i] << std::endl;
     }
     std::cout << std::endl;
 }
read_dict_from_file()
void read_dict_from_file (const std::string & dictionary_filename, std::vector< std::string > & dictionary)
reading dictionary from file
Parameters
dictionary_filename - the filename that need to be read
dictionary - contain all words in the file
Definition at line 56 of file functions.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     std::ifstream file(dictionary_filename);
     size_t counter = 0;
     if (file.is_open())
     {
         std::string line;
         size_t i = 0;
         while (std::getline(file, line))
         {
             dictionary[i++] = line;
             counter++;
         }
         dictionary.resize(counter);
         file.close();
     }
     else
     {
         BOOST_LOG_TRIVIAL(error) << "Couldn't open " << dictionary_filename << " for reading";
         std::cerr << "Couldn't open " << dictionary_filename << " for reading\n";
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "read_dict_from_file()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
read_from_file()
void read_from_file (const std::string & text_filename, std::string & text)
Definition at line 484 of file functions.cpp.
 {
     std::ifstream file(text_filename);
     if (file.is_open())
     {
         std::string line;
         while (std::getline(file, line))
         {
             text += line;
             text += " ";
         }
         file.close();
     }
     else
     {
         std::cerr << "Couldn't open " << "text.txt" << " for reading\n";
     }
 }
read_text_from_file()
void read_text_from_file (const std::string & text_filename, std::vector< std::string > & text)
reading input text, stop words from file
Parameters
text_filename - the filename that need to be read
text - contain all words in the file
Definition at line 83 of file functions.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     std::ifstream file(text_filename);
     if (file.is_open())
     {
         std::string line;
         size_t i = 0, counter = 0;
         while (std::getline(file, line))
         {
             //std::cout << line << " " << line.size() << std::endl;
             size_t size = line.size();;
             if(line[size - 1] < 'A' || line[size - 1] > 'Z' &&
                 line[size - 1] < 'a' || line[size - 1] > 'z')
             {
                 line.pop_back();
             }
             char* str = &line[0];
             char* pch;
             pch = strtok(str, " ,.-?");
             //std::cout << line << " " << line.size() << std::endl;
             while (pch != NULL)
             {
                 for (size_t j = 0; j < strlen(pch); j++)
                 {
                     if (pch[j] >= 65 && pch[j] <= 92)
                     {
                         pch[j] = pch[j] + 32;
                     }
                 }
                 //std::cout << pch << " " << strlen(pch) << std::endl;
                 text[i++] = pch;
                 pch = strtok(NULL, " ,.-?");
                 counter++;
             }
         }
         text.resize(counter);
         file.close();
     }
     else
     {
         BOOST_LOG_TRIVIAL(error) << "Couldn't open " << text_filename << " for reading";
         std::cerr << "Couldn't open " << text_filename << " for reading\n";
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "read_from_text_file()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }
search_and_calculate_matrices()
void search_and_calculate_matrices (std::bitset< 100 > & output, std::map< std::string, size_t > & words_count, const std::vector< size_t > & text_single_term_hashes, const std::vector< size_t > & text_double_term_hashes, const std::vector< size_t > & text_triple_term_hashes, const std::vector< size_t > & stop_words_hashes, const std::vector< std::pair< size_t, size_t >> & hash_table, const std::vector< std::bitset< 100 >> & matrices, const std::vector< std::string > & dictionary)
correcting input text hashes, maybe there are duplicates
Parameters
output - the result of the program, score of the sentence
text_single_term_hashes - hash of text, contain hashed strings of each word in text
text_double_term_hashes - hash of text, contain hashed strings of each double combination of words in text
stop_words_hashes - contain all hashes of stop words
hash_table - hash table contain hashes and indexes to the words in dictionary
matrices - vector of bitsets, contain all initialized matrices of length 100
dictionary - conatin all words in dictionary.txt
Definition at line 255 of file functions.cpp.
References dict_size, hash_table(), matrices(), matrix_size, text_double_term_hashes(), text_single_term_hashes(), text_size, and text_triple_term_hashes().
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     auto start = std::chrono::steady_clock::now();
     size_t text_size = text_single_term_hashes.size();
     size_t dict_size = dictionary.size();
     size_t matrix_size = output.size();
     std::vector<size_t> indexes(text_size);
     std::vector<const std::vector<size_t>*> terms(3);
     terms[0] = &text_single_term_hashes;
     terms[1] = &text_double_term_hashes;
     terms[2] = &text_triple_term_hashes;
     for(size_t k = 3; k > 0; --k)
     {
         for (size_t i = 0; i < text_size - k + 1; ++i)
         {
             bool b = true;
             for(size_t l = 0; l < k; ++l)
             {
                 if (indexes[i + l])
                 {
                     b = false;
                 }
             }
             if(k == 1)
             {
                 for (size_t l = 0; l < stop_words_hashes.size(); ++l)
                 {
                     if (stop_words_hashes[l] == (*terms[0])[i])
                     {
                         indexes[i] = 1;
                         b = false;
                     }
                 }
             }
             if (b)
             {
                 size_t index = ((*terms[k - 1])[i]) % dict_size;
                 for (size_t j = 0; j < dict_size; ++j)
                 {
                     if (hash_table[index].first == ((*terms[k - 1])[i]))
                     {
                         for(size_t l = 0; l < k; ++l)
{
                             indexes[i + l] = 1;
                         }
                         output |= matrices[hash_table[index].second];
                         size_t& value = words_count[dictionary[hash_table[index].second]];
                         value? value++ : value = 1;
                         break;
                     }
                     else
                     {
                         index = (index + 1) % dict_size;
                     }
                 }
             }
         }
     }
     auto end = std::chrono::steady_clock::now();
     BOOST_LOG_TRIVIAL(debug) << "search_and_calculate_matrices()  "
         << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms";
 }