Calculate sentence score: src/unit_tests.cpp File Reference
unit_tests.cpp File Reference
#include "functions.hpp"
#include <unordered_set>
#include <bitset>
#include <boost/test/unit_test.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/core.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/log/utility/setup/common_attributes.hpp>
Macros
#define BOOST_TEST_MODULE functions
#define max_dict_size 500000
#define max_term_size 20000
#define max_stop_words_size 200
#define matrix_size 100
Functions
std::vector< std::string > dictionary (500000)
std::vector< size_t > dict_hashes (500000)
std::vector< std::string > text (20000)
std::vector< size_t > text_single_term_hashes (20000)
std::vector< size_t > text_double_term_hashes (20000)
std::vector< size_t > text_triple_term_hashes (20000)
std::vector< std::string > stop_words (200)
std::vector< size_t > stop_words_hashes (200)
std::vector< std::pair< size_t, size_t > > hash_table (500000)
std::vector< std::bitset< 100 > > matrices (500000)
std::bitset< 100 > output (100)
BOOST_AUTO_TEST_CASE (read_dict_from_file_test)
BOOST_AUTO_TEST_CASE (read_text_from_file_test)
BOOST_AUTO_TEST_CASE (init_random_matrices_test)
BOOST_AUTO_TEST_CASE (init_hashes_test)
BOOST_AUTO_TEST_CASE (correct_dict_hashes_and_extract_duplicates_test)
BOOST_AUTO_TEST_CASE (hash_function_test)
BOOST_AUTO_TEST_CASE (search_and_calculate_matrices_test)
Variables
std::hash< std::string > hasher
const std::string dictionary_filename = "dictionary.txt"
size_t dict_size
const std::string text_filename = "text1.txt"
size_t text_size
const std::string stop_words_filename = "stop_words.txt"
size_t stop_words_size
std::vector< std::vector< size_t > > duplicates
size_t duplicates_size
std::map< std::string, size_t > words_count
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE functions
Definition at line 1 of file unit_tests.cpp.
matrix_size
#define matrix_size 100
Definition at line 17 of file unit_tests.cpp.
max_dict_size
#define max_dict_size 500000
Definition at line 14 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
max_stop_words_size
#define max_stop_words_size 200
Definition at line 16 of file unit_tests.cpp.
max_term_size
#define max_term_size 20000
Definition at line 15 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (read_dict_from_file_test)
Definition at line 47 of file unit_tests.cpp.
References dict_size, dictionary(), dictionary_filename, max_dict_size, and read_dict_from_file().
 {
     read_dict_from_file(dictionary_filename, dictionary);
     dict_size = dictionary.size();
     BOOST_REQUIRE_LE( dict_size, max_dict_size);
     for(size_t i = 0; i < dict_size; ++i)
     {
         BOOST_CHECK_NE(dictionary[i].size(), 0);
         for(size_t j = 0; j < dictionary[i].size(); ++j)
         {
             // Decimal 32 = [Space] character
             // Decimal 127 = [DEL] character
             // (32, 127) in this area characters are visible
             BOOST_WARN(dictionary[i][j] > 32 &&
                         dictionary[i][j] < 127);
         }
     }
 }
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (read_text_from_file_test)
Definition at line 66 of file unit_tests.cpp.
References max_term_size, read_text_from_file(), stop_words(), stop_words_filename, stop_words_size, text(), text_filename, and text_size.
 {
     read_text_from_file(text_filename, text);
     text_size = text.size();
     BOOST_REQUIRE_LE( text_size, max_term_size);
     for(size_t i = 0; i < text_size; ++i)
     {
         BOOST_CHECK_NE(text[i].size(), 0);
         for(size_t j = 0; j < text[i].size(); ++j)
         {
             // Decimal 32 = [Space] character
             // Decimal 127 = [DEL] character
             // (32, 127) in this area characters are visible
             BOOST_WARN(text[i][j] > 32 &&
                     text[i][j] < 127);
         }
     }
     read_text_from_file(stop_words_filename, stop_words);
     stop_words_size = stop_words.size();
     BOOST_REQUIRE_LE( stop_words_size, max_term_size);
     for(size_t i = 0; i < stop_words_size; ++i)
     {
         BOOST_CHECK_NE(stop_words[i].size(), 0);
         for(size_t j = 0; j < stop_words[i].size(); ++j)
         {
             // Decimal 32 = [Space] character
             // Decimal 127 = [DEL] character
             // (32, 127) in this area characters are visible
             BOOST_WARN(stop_words[i][j] > 32 &&
                     stop_words[i][j] < 127);
         }
     }
 }
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (init_random_matrices_test)
Definition at line 101 of file unit_tests.cpp.
References dict_size, init_random_matrices(), and matrices().
 {
     matrices.resize(dict_size);
     init_random_matrices(matrices);
     size_t size = matrices.size();
     std::unordered_set<std::bitset<matrix_size>> un_set(matrices.begin(),matrices.end());
     BOOST_WARN_EQUAL(un_set.size(), size);
 }
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (init_hashes_test)
Definition at line 110 of file unit_tests.cpp.
References dict_hashes(), dict_size, dictionary(), hasher, init_hashes(), stop_words(), stop_words_hashes(), stop_words_size, text(), text_double_term_hashes(), text_single_term_hashes(), text_size, and text_triple_term_hashes().
 {
     dict_hashes.resize(dict_size);
     init_hashes(dict_hashes, hasher, dictionary);
     BOOST_CHECK_EQUAL(dict_hashes.size(), dict_size);
     size_t size = dict_hashes.size();
     std::unordered_set<std::bitset<matrix_size>> un_set(dict_hashes.begin(),dict_hashes.end());
     BOOST_WARN_EQUAL( un_set.size(), size );
     un_set.clear();
     text_single_term_hashes.resize(text_size);
     init_hashes(text_single_term_hashes, hasher, text);
     BOOST_WARN_EQUAL(text_single_term_hashes.size(), text_size);
     size = text_single_term_hashes.size();
     un_set = std::unordered_set<std::bitset<matrix_size>>(text_single_term_hashes.begin(),text_single_term_hashes.end());
     BOOST_WARN_LE( un_set.size(), size );
     un_set.clear();
     text_double_term_hashes.resize(text_size - 1);
     init_hashes(text_double_term_hashes, hasher, text);
     BOOST_CHECK_EQUAL(text_double_term_hashes.size(), text_size - 1);
     size = text_double_term_hashes.size();
     un_set = std::unordered_set<std::bitset<matrix_size>>(text_double_term_hashes.begin(),text_double_term_hashes.end());
     BOOST_WARN_LE( un_set.size(), size );
     un_set.clear();
     text_triple_term_hashes.resize(text_size - 2);
     init_hashes(text_triple_term_hashes, hasher, text);
     BOOST_CHECK_EQUAL(text_triple_term_hashes.size(), text_size - 2);
     size = text_triple_term_hashes.size();
     un_set = std::unordered_set<std::bitset<matrix_size>>(text_triple_term_hashes.begin(),text_triple_term_hashes.end());
     BOOST_WARN_LE( un_set.size(), size );
     un_set.clear();
     stop_words_hashes.resize(stop_words_size);
     init_hashes(stop_words_hashes, hasher, stop_words);
     BOOST_CHECK_EQUAL(stop_words_hashes.size(),stop_words_size);
     size = stop_words_hashes.size();
     un_set = std::unordered_set<std::bitset<matrix_size>>(stop_words_hashes.begin(),stop_words_hashes.end());
     BOOST_WARN_EQUAL( un_set.size(), size );
 }
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (correct_dict_hashes_and_extract_duplicates_test)
Definition at line 153 of file unit_tests.cpp.
References correct_dict_hashes_and_extract_duplicates(), dict_hashes(), dict_size, and duplicates_size.
 {
     correct_dict_hashes_and_extract_duplicates(duplicates,dict_hashes);
     size_t duplicates_size = duplicates.size();
     BOOST_CHECK_EQUAL(duplicates_size, 0);
     BOOST_CHECK_EQUAL(dict_hashes.size(), dict_size);
     size_t size = dict_hashes.size();
     std::unordered_set<std::bitset<matrix_size>> un_set(dict_hashes.begin(),dict_hashes.end());
     BOOST_WARN_EQUAL( un_set.size(), size );
 }
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (hash_function_test)
Definition at line 164 of file unit_tests.cpp.
References dict_hashes(), dict_size, hash_function(), and hash_table().
 {
     hash_table.resize(dict_size);
     hash_function(hash_table, dict_hashes);
     BOOST_CHECK_EQUAL(hash_table.size(), dict_hashes.size());
     for(size_t i = 0; i < dict_size; ++i)
     {
         BOOST_CHECK_NE(hash_table[i].first,0);
     }
 }
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (search_and_calculate_matrices_test)
Definition at line 175 of file unit_tests.cpp.
References dictionary(), hash_table(), matrices(), output(), search_and_calculate_matrices(), stop_words_hashes(), text_double_term_hashes(), text_single_term_hashes(), and text_triple_term_hashes().
 {
     std::bitset<matrix_size> temp = output;
     search_and_calculate_matrices(output, words_count, text_single_term_hashes, text_double_term_hashes,
         text_triple_term_hashes, stop_words_hashes, hash_table, matrices, dictionary);
     BOOST_CHECK_NE(temp, output);
 }
dict_hashes()
std::vector<size_t> dict_hashes (500000)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
dictionary()
std::vector<std::string> dictionary (500000)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
hash_table()
std::vector<std::pair<size_t,size_t> > hash_table (500000)
Referenced by BOOST_AUTO_TEST_CASE(), hash_function(), main(), print_hash_table(), and search_and_calculate_matrices().
matrices()
std::vector<std::bitset< 100 > > matrices (500000)
Referenced by BOOST_AUTO_TEST_CASE(), init_random_matrices(), main(), and search_and_calculate_matrices().
output()
std::bitset< 100 > output (100)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
stop_words()
std::vector<std::string> stop_words (200)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
stop_words_hashes()
std::vector<size_t> stop_words_hashes (200)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
text()
std::vector<std::string> text (20000)
Referenced by BOOST_AUTO_TEST_CASE(), and main().
text_double_term_hashes()
std::vector<size_t> text_double_term_hashes (20000)
Referenced by BOOST_AUTO_TEST_CASE(), main(), and search_and_calculate_matrices().
text_single_term_hashes()
std::vector<size_t> text_single_term_hashes (20000)
Referenced by BOOST_AUTO_TEST_CASE(), main(), and search_and_calculate_matrices().
text_triple_term_hashes()
std::vector<size_t> text_triple_term_hashes (20000)
Referenced by BOOST_AUTO_TEST_CASE(), main(), and search_and_calculate_matrices().
Variable Documentation
dict_size
size_t dict_size
Definition at line 24 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), init_random_matrices(), main(), and search_and_calculate_matrices().
dictionary_filename
const std::string dictionary_filename = "dictionary.txt"
Definition at line 21 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
duplicates
std::vector<std::vector<size_t> > duplicates
Definition at line 38 of file unit_tests.cpp.
Referenced by correct_dict_hashes_and_extract_duplicates(), correct_text_hashes(), main(), and print_duplicates().
duplicates_size
size_t duplicates_size
Definition at line 39 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
hasher
std::hash<std::string> hasher
Definition at line 19 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), init_hashes(), and main().
stop_words_filename
const std::string stop_words_filename = "stop_words.txt"
Definition at line 33 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
stop_words_size
size_t stop_words_size
Definition at line 36 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
text_filename
const std::string text_filename = "text1.txt"
Definition at line 26 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
text_size
size_t text_size
Definition at line 31 of file unit_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), correct_text_hashes(), main(), and search_and_calculate_matrices().
words_count
std::map<std::string, size_t> words_count
Definition at line 43 of file unit_tests.cpp.
Referenced by hash_function(), and main().